sudo: required

services:
  -docker

before_install:
  - docker build -t imanr76/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imanr76/react-test npm test

after-success:
  - docker build -t imanr76/multi-client ./client
  - docker build -t imanr76/multi-nginx ./nginx
  - docker build -t imanr76/multi-server ./server
  - docker build -t imanr76/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push imar76/multi-client 
  - docker push imar76/multi-nginx 
  - docker push imar76/multi-server 
  - docker push imar76/multi-worker 